# Generated by Django 3.0.7 on 2020-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='pos_tag',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='definition',
            name='sub_definitions',
            field=models.ManyToManyField(blank=True, related_name='_definition_sub_definitions_+', to='dictionary.Definition'),
        ),
    ]
