# Generated by Django 3.0.7 on 2020-07-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20200711_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoS_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20)),
                ('absolute_frequency', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='pos_tag',
            new_name='local_pos_tag',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='collocations',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='sub_definitions',
        ),
        migrations.AddField(
            model_name='lemma',
            name='collocations',
            field=models.ManyToManyField(to='dictionary.Collocation'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='disambiguations',
            field=models.ManyToManyField(blank=True, related_name='disambiguation_definitions', to='dictionary.Definition'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='frequency_w2v',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lemma',
            name='global_pos_tags',
            field=models.ManyToManyField(to='dictionary.PoS_tag'),
        ),
    ]
