# Generated by Django 3.0.7 on 2020-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20200712_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='negative_lemmas',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='vector_lemmas',
        ),
        migrations.AddField(
            model_name='lemma',
            name='vector_lemmas',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
