# Generated by Django 3.0.7 on 2020-07-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20200713_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context_tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
