# Generated by Django 3.0.7 on 2020-07-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_context_token_similarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos_tag',
            name='absolute_frequency',
        ),
        migrations.CreateModel(
            name='pos_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_frequency', models.IntegerField()),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.PoS_tag')),
            ],
        ),
    ]
