# Generated by Django 3.0.7 on 2020-07-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=5000)),
                ('singular', models.CharField(max_length=20)),
                ('plural', models.CharField(max_length=20)),
                ('collocations', models.ManyToManyField(to='dictionary.Collocation')),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=200)),
                ('definition', models.ManyToManyField(to='dictionary.Definition')),
                ('vector_lemmas', models.ManyToManyField(blank=True, related_name='_lemma_vector_lemmas_+', to='dictionary.Lemma')),
            ],
        ),
    ]
