# Generated by Django 3.0.7 on 2020-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20200610_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='definition_summary',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='definition_vector',
        ),
        migrations.AddField(
            model_name='lemma',
            name='vector_lemmas',
            field=models.ManyToManyField(blank=True, related_name='_lemma_vector_lemmas_+', to='dictionary.Lemma'),
        ),
    ]
