# Generated by Django 3.0.7 on 2020-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20200712_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='frequency_w2v',
            field=models.IntegerField(blank=True),
        ),
    ]
